server:
  port: 8080

spring:
  application:
    name: suyasuya-backend

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suyasuya?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 13579Fzp
    druid:
      initial-size: 5   # 初始创建连接数
      max-active: 100   # 最大连接数量
      max-wait: 3000    # 最大等待时间（毫秒）

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  mail:
    host: smtp.qq.com             #邮件服务器地址
    protocol: smtp                #协议
    username: 823272539@qq.com    #发送邮件的邮箱也就是你开通服务的邮箱
    password: wpmwdagjgafnbbbf    #开通服务后得到的授权码
    default-encoding: utf-8       #邮件内容的编码
    port: 465                     #SMTP SSL 默认端口
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true  # 启用 SSL

  servlet:
    multipart:
      max-file-size: 5GB          #文件上传的大小限制
      max-request-size: 5GB

jwt:
  secret-key: "fdasfgdsagaxgsregdfdjyghjfhebfdgwe45ygrfbsdfshfdsag"
  expiration-time: 86400000  # 令牌有效期：24小时（毫秒）

# 文件上传路径  注意要与资源映射路径相匹配
upload:
  video:
    path: D:\\web\\uploads\\video
  cover:
    path: D:\\web\\uploads\\cover
  avatar:
    path: D:\\web\\uploads\\avatar
  temporarily:
    path: D:\\web\\uploads\\temporarily

video:
  ffmpeg-path: D:\\DevelopmentEnvironment\\ffmpeg-2025-02-17-git-b92577405b-full_build\\bin\\ffprobe.exe

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.demo.entity,com.example.demo.vo

logging:
  level:
    org.springframework.mail: DEBUG

search:
  history:
    interval-minutes: 10  # 搜索历史去重时间间隔（分钟）